=== JoranSlingerland/StockTracker/.data/input/input_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "transactions": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "symbol": {
                            "description": "The ticker symbol of the stock",
                            "type": "string"
                        },
                        "transaction_date": {
                            "description": "The date of the transaction",
                            "type": "string",
                            "format": "date"
                        },
                        "cost": {
                            "description": "The cost of the transaction",
                            "type": "number",
                            "minimum": 0
                        },
                        "quantity": {
                            "description": "The quantity of the transaction",
                            "type": "number",
                            "minimum": 0
                        },
                        "transaction_type": {
                            "description": "The type of transaction",
                            "type": "string",
                            "enum": [
                                "Buy",
                                "Sell"
                            ]
                        },
                        "transaction_cost": {
                            "description": "The cost of the transaction",
                            "type": "number",
                            "minimum": 0
                        },
                        "currency": {
                            "description": "The currency of the stock",
                            "type": "string",
                            "enum": [
                                "AED",
                                "AFN",
                                "ALL",
                                "AMD",
                                "ANG",
                                "AOA",
                                "ARS",
                                "AUD",
                                "AWG",
                                "AZN",
                                "BAM",
                                "BBD",
                                "BDT",
                                "BGN",
                                "BHD",
                                "BIF",
                                "BMD",
                                "BND",
                                "BOB",
                                "BRL",
                                "BSD",
                                "BTN",
                                "BWP",
                                "BYR",
                                "BZD",
                                "CAD",
                                "CDF",
                                "CHF",
                                "CLP",
                                "CNY",
                                "COP",
                                "CRC",
                                "CUC",
                                "CVE",
                                "CZK",
                                "DJF",
                                "DKK",
                                "DOP",
                                "DZD",
                                "EEK",
                                "EGP",
                                "ERN",
                                "ETB",
                                "EUR",
                                "FJD",
                                "FKP",
                                "GBP",
                                "GEL",
                                "GHS",
                                "GIP",
                                "GMD",
                                "GNF",
                                "GQE",
                                "GTQ",
                                "GYD",
                                "HKD",
                                "HNL",
                                "HRK",
                                "HTG",
                                "HUF",
                                "IDR",
                                "ILS",
                                "INR",
                                "IQD",
                                "IRR",
                                "ISK",
                                "JMD",
                                "JOD",
                                "JPY",
                                "KES",
                                "KGS",
                                "KHR",
                                "KMF",
                                "KPW",
                                "KRW",
                                "KWD",
                                "KYD",
                                "KZT",
                                "LAK",
                                "LBP",
                                "LKR",
                                "LRD",
                                "LSL",
                                "LTL",
                                "LVL",
                                "LYD",
                                "MAD",
                                "MDL",
                                "MGA",
                                "MKD",
                                "MMK",
                                "MNT",
                                "MOP",
                                "MRO",
                                "MUR",
                                "MVR",
                                "MWK",
                                "MXN",
                                "MYR",
                                "MZM",
                                "NAD",
                                "NGN",
                                "NIO",
                                "NOK",
                                "NPR",
                                "NZD",
                                "OMR",
                                "PAB",
                                "PEN",
                                "PGK",
                                "PHP",
                                "PKR",
                                "PLN",
                                "PYG",
                                "QAR",
                                "RON",
                                "RSD",
                                "RUB",
                                "SAR",
                                "SBD",
                                "SCR",
                                "SDG",
                                "SEK",
                                "SGD",
                                "SHP",
                                "SLL",
                                "SOS",
                                "SRD",
                                "SYP",
                                "SZL",
                                "THB",
                                "TJS",
                                "TMT",
                                "TND",
                                "TRY",
                                "TTD",
                                "TWD",
                                "TZS",
                                "UAH",
                                "UGX",
                                "USD",
                                "UYU",
                                "UZS",
                                "VEB",
                                "VND",
                                "VUV",
                                "WST",
                                "XAF",
                                "XCD",
                                "XDR",
                                "XOF",
                                "XPF",
                                "YER",
                                "ZAR",
                                "ZMK",
                                "ZWR"
                            ]
                        }
                    },
                    "required": [
                        "symbol",
                        "transaction_date",
                        "cost",
                        "quantity",
                        "transaction_type",
                        "transaction_cost",
                        "currency"
                    ]
                }
            ]
        },
        "cash": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "transaction_date": {
                        "description": "The date of the transaction",
                        "type": "string",
                        "format": "date"
                    },
                    "transaction_type": {
                        "description": "The type of transaction",
                        "type": "string",
                        "enum": [
                            "Deposit",
                            "Withdrawal"
                        ]
                    },
                    "amount": {
                        "description": "The amount of the transaction",
                        "type": "number"
                    }
                },
                "required": [
                    "transaction_date",
                    "transaction_type",
                    "amount"
                ]
            }
        },
        "api_key": {
            "type": "string"
        },
        "sql_server": {
            "type": "object",
            "properties": {
                "server": {
                    "type": "string",
                    "description": "The SQL Server name"
                },
                "database": {
                    "type": "string",
                    "description": "The SQL Server database"
                },
                "user": {
                    "type": "string",
                    "description": "The SQL Server user"
                },
                "password": {
                    "type": "string",
                    "description": "The SQL Server password"
                },
                "tables": {
                    "type": "array",
                    "description": "The SQL Server tables",
                    "items": [
                        {
                            "type": "object",
                            "properties": {
                                "table_name": {
                                    "type": "string"
                                },
                                "columns": {
                                    "type": "object",
                                    "properties": {
                                        "date": {
                                            "type": "string"
                                        },
                                        "amount": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "date",
                                        "amount"
                                    ]
                                }
                            },
                            "required": [
                                "table_name",
                                "columns"
                            ]
                        },
                        {
                            "type": "object",
                            "properties": {
                                "table_name": {
                                    "type": "string"
                                },
                                "columns": {
                                    "type": "object",
                                    "properties": {
                                        "date": {
                                            "type": "string"
                                        },
                                        "average_cost": {
                                            "type": "string"
                                        },
                                        "close_value": {
                                            "type": "string"
                                        },
                                        "currency": {
                                            "type": "string"
                                        },
                                        "high_value": {
                                            "type": "string"
                                        },
                                        "low_value": {
                                            "type": "string"
                                        },
                                        "open_value": {
                                            "type": "string"
                                        },
                                        "quantity": {
                                            "type": "string"
                                        },
                                        "symbol": {
                                            "type": "string"
                                        },
                                        "total_cost": {
                                            "type": "string"
                                        },
                                        "transaction_cost": {
                                            "type": "string"
                                        },
                                        "volume": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "date",
                                        "average_cost",
                                        "close_value",
                                        "currency",
                                        "high_value",
                                        "low_value",
                                        "open_value",
                                        "quantity",
                                        "symbol",
                                        "total_cost",
                                        "transaction_cost",
                                        "volume"
                                    ]
                                }
                            },
                            "required": [
                                "table_name",
                                "columns"
                            ]
                        },
                        {
                            "type": "object",
                            "properties": {
                                "table_name": {
                                    "type": "string"
                                },
                                "columns": {
                                    "type": "object",
                                    "properties": {
                                        "date": {
                                            "type": "string"
                                        },
                                        "total_cost": {
                                            "type": "string"
                                        },
                                        "total_value": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "date",
                                        "total_cost",
                                        "total_value"
                                    ]
                                }
                            },
                            "required": [
                                "table_name",
                                "columns"
                            ]
                        }
                    ]
                }
            },
            "required": [
                "server",
                "database",
                "user",
                "password"
            ]
        }
    },
    "required": [
        "transactions",
        "api_key",
        "cash"
    ]
}

=== JoranSlingerland/StockTracker/.data/input/sample.json
{
    "$schema": "https://raw.githubusercontent.com/JoranSlingerland/StockTracker/main/.data/input/input_schema.json",
    "transactions": [
        {
            "symbol": "AAPL",
            "transaction_date": "2019-01-21",
            "cost": 100.00,
            "quantity": 100,
            "transaction_type": "Buy",
            "transaction_cost": 0.50,
            "currency": "USD"
        },
        {
            "symbol": "AAPL",
            "transaction_date": "2020-01-21",
            "cost": 125.00,
            "quantity": 100,
            "transaction_type": "Buy",
            "transaction_cost": 0.50,
            "currency": "USD"
        },
        {
            "symbol": "MSFT",
            "transaction_date": "2021-10-24",
            "cost": 100.00,
            "quantity": 100,
            "transaction_type": "Buy",
            "transaction_cost": 0.50 ,
            "currency": "USD"
        }
    ],
    "cash": [
        {
            "transaction_date": "2019-01-21",
            "transaction_type": "Deposit",
            "amount": 125.00
        },
        {
            "transaction_date": "2020-01-21",
            "transaction_type": "Withdrawal",
            "amount": 100.00
        },
        {
            "transaction_date": "2021-10-24",
            "transaction_type": "Deposit",
            "amount": 100.00
        }
    ],
    "api_key": "ABCD1234EFGH5678",
    "sql_server": {
        "server": "localhost",
        "database": "StockTracker",
        "user": "sa",
        "password": "Password123",
        "tables": [
            {
                "table_name": "cash_held",
                "columns": {
                    "date": "DATE",
                    "amount": "MONEY"
                }
            },
            {
                "table_name": "stocks_held",
                "columns": {
                    "date": "DATE",
                    "symbol": "TEXT",
                    "average_cost": "MONEY",
                    "total_cost": "MONEY",
                    "quantity": "DECIMAL(38,2)",
                    "transaction_cost": "MONEY",
                    "currency": "TEXT",
                    "close_value": "MONEY",
                    "high_value": "MONEY",
                    "low_value": "MONEY",
                    "open_value": "MONEY",
                    "volume": "DECIMAL(38,2)",
                    "total_value": "MONEY"
                }
            },
            {
                "table_name": "totals",
                "columns": {
                    "date": "DATE",
                    "total_cost": "MONEY",
                    "total_value": "MONEY"
                }
            },
            {
                "table_name": "single_day",
                "columns": {
                    "symbol": "TEXT",
                    "average_cost": "MONEY",
                    "total_cost": "MONEY",
                    "quantity": "DECIMAL(38,2)",
                    "transaction_cost": "MONEY",
                    "currency": "TEXT",
                    "close_value": "MONEY",
                    "high_value": "MONEY",
                    "low_value": "MONEY",
                    "open_value": "MONEY",
                    "volume": "DECIMAL(38,2)",
                    "total_value": "MONEY"
                }
            }
        ]
    }
}
